name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex
          args: -shell-escape -pdf -file-line-error -halt-on-error -interaction=nonstopmode
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: report.pdf
